/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
export const Stats = IDL.Record({
  'happyCustomers' : IDL.Nat,
  'yearsExperience' : IDL.Nat,
  'citiesServed' : IDL.Nat,
  'projectsCompleted' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const Stats = IDL.Record({
    'happyCustomers' : IDL.Nat,
    'yearsExperience' : IDL.Nat,
    'citiesServed' : IDL.Nat,
    'projectsCompleted' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };